# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    parsermarkdown.urlreadme: https://raw.githubusercontent.com/Emergya/SymfonyZero-API/master/README.md
    
services:
    symfonyzero_api.parsermarkdown:
        class:      ApiBundle\Services\ParserMarkdown
        arguments:  ["%parsermarkdown.urlreadme%"]
    
    symfonyzero.elastica_to_model_transformer:
        class: ApiBundle\Transformer\ElasticaResultTransformer
    
    #symfonyzero.elastica_listener_users: 
    #    class: ApiBundle\Listener\UsersListener
    #    #Object_persister: entity indexed at elasticsearch.yml config file 
    #    arguments:
    #        - @fos_elastica.object_persister.symfonyzero.user
    #        - @fos_elastica.indexable
    #    calls:
    #        - [ setContainer, ['@service_container'] ]
    #    tags:
    #        - { name: doctrine.event_listener, event: postPersist }
    #        - { name: doctrine.event_listener, event: postUpdate }
    #        - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
    